name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
      BASEIMAGETAG: "poi-image"
      ACRNAME: "openhackahx2xw01acr"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Image
      run: |
            echo "Building API-POI image..."
            echo "Changing directory to /web..."
            cd /web
            az acr build --image "devopsoh/api-poi:${BASEIMAGETAG}" --registry $ACRNAME --file Dockerfile'
