name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
      BASEIMAGETAG: "poi-image"
      ACRNAME: "openhackahx2xw01acr"
      GITOHTEAMDIRPATH: "OpenHack-DevOps-Team7"
      TEST: "test"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Log in with Azure
      uses: azure/login@v1
      with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
    - name: Image
      run: |
            echo "Building API-POI image..."
            #echo "repo $GITHUB_REPOSITORY"
            #echo "ws $GITHUB_WORKSPACE"
            #echo "action path $GITHUB_ACTION_PATH"
            cd /home/runner/work/poi/poi/web
            az acr build --image "devopsoh/api-poi:v_${{github.run_number}}" --registry $ACRNAME --file Dockerfile .
            
   
    - name: App deployment
      uses: azure/webapps-deploy@v2      
      with:
        slot-name: 'staging'        
        app-name: 'openhackahx2xw01poi'        
        images: 'openhackahx2xw01acr.azurecr.io/devopsoh/api-poi:v_${{github.run_number}}'

    #- name: HealthTest1
    #  run: powershell .\Polling.ps1 https://openhackahx2xw01poi-staging.azurewebsites.net/api/healthcheck/poi


    #- name: Healthcheck
    #  shell: pwsh
    #  run: |
    #  .\Polling.ps1
    - name: Swap staging slot into production
      id: slot_swap
      run: |
        az webapp deployment slot swap -g "openhackahx2xw01rg" -n "openhackahx2xw01poi" -s staging
        url=$(az webapp show -g "openhackahx2xw01rg" -n "openhackahx2xw01poi" --query "defaultHostName" -o tsv)
        echo "::set-output name=url::http://$url"


