name: rollback
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Log in with Azure
      uses: azure/login@v1
      with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
    - name: Start staging
      run: |
        az webapp start --name openhackahx2xw01poi -s staging  --resource-group openhackahx2xw01rg
    - name: Swap Prod into staging
      id: slot_swap
      run: |
        az webapp deployment slot swap -g "openhackahx2xw01rg" -n "openhackahx2xw01poi" -s staging
        url=$(az webapp show -g "openhackahx2xw01rg" -n "openhackahx2xw01poi" --query "defaultHostName" -o tsv)
        echo "::set-output name=url::http://$url"
    - name: Stop staging
      run: |
        az webapp stop --name openhackahx2xw01poi -s staging  --resource-group openhackahx2xw01rg
